<?php
ini_set("include_path", "../Rackspace/Cloud".PATH_SEPARATOR."../../../Rackspace/Cloud".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once 'Servers.php';

/**
 * Test class for Rackspace_Cloud_Servers.
 * Generated by PHPUnit on 2009-09-29 at 09:25:38.
 */
class Rackspace_Cloud_ServersTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Rackspace_Cloud_Servers
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetServers().
     */
    public function testGetServers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetServerDetails().
     */
    public function testGetServerDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFlavorDetails().
     */
    public function testGetFlavorDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetHttpClient().
     */
    public function testGetHttpClient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
