<?php
ini_set("include_path", "..".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';
require_once 'RackspaceTestAbstract.php';

require_once 'Rackspace.php';

/**
 * Test class for Rackspace.
 * Generated by PHPUnit on 2009-09-29 at 09:25:38.
 */
class RackspaceTest extends RackspaceTestAbstract
{
    /**
     * @var    Rackspace
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testGetInstance() {
		$this->checkConfig();
		$servers = Rackspace::getInstance(Rackspace::SERVICE_CLOUD_SERVERS);
		$this->assertType('Rackspace_Cloud_Servers', $servers);
    }

    public function testGetHttpClient() {
		$this->checkConfig();

		$http = Rackspace::getHttpClient();
		$this->assertType('Zend_Http_Client', $http);
    }

	public function testAuthBad() {
		$this->setExpectedException('Rackspace_Exception');

		Rackspace::$username = 'foo';
		Rackspace::$api_key = 'bar';
		$auth = Rackspace::auth();
	}

    public function testAuth() {
		$this->checkConfig();

		Rackspace::$username = RACKSPACE_CLOUD_SERVER_USER;
		Rackspace::$api_key = RACKSPACE_CLOUD_SERVER_API_KEY;
		$auth = Rackspace::auth();
    }
}
?>
