<?php
ini_set("include_path", "../Rackspace/Cloud/Servers".PATH_SEPARATOR."../../../../Rackspace/Cloud/Servers".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once 'Flavor.php';

/**
 * Test class for Rackspace_Cloud_Servers_Flavor.
 * Generated by PHPUnit on 2009-09-29 at 09:25:40.
 */
class Rackspace_Cloud_Servers_FlavorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Rackspace_Cloud_Servers_Flavor
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }
}
?>
