<?php
ini_set("include_path", "../Rackspace/Cloud/Servers".PATH_SEPARATOR."../../../../Rackspace/Cloud/Servers".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once 'Instance.php';

/**
 * Test class for Rackspace_Cloud_Servers_Instance.
 * Generated by PHPUnit on 2009-09-29 at 09:25:39.
 */
class Rackspace_Cloud_Servers_InstanceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Rackspace_Cloud_Servers_Instance
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetIPs().
     */
    public function testGetIPs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPublicIPs().
     */
    public function testGetPublicIPs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPrivateIPs().
     */
    public function testGetPrivateIPs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFlavor().
     */
    public function testGetFlavor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testReboot().
     */
    public function testReboot() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
